### ISSUE TITLE
Java VM does not exist

### ISSUE THREAD

**Issue by lafita** [EBI-predocs/research-software#71]
When I run java in `/nfs/software/software/prefix/usr/bin/java` I get the following error:

```
* Home for VM '' does not exist: 
* Invalid System VM: 
```

If I run the java in `/usr/bin/java` it works fine, so it is not due to some environmental variables or java configuration.

I also tried unsuccessfully googling the error, because the message is printed by the script `/nfs/software/software/prefix/usr/bin/java` itself, which does some complex operations with the VM path.

Did anyone else notice this? Any ideas how to solve it?

**Comment by mattjeffryes** [comment]
I didn't install Java properly when we rebuilt the prefix installation. Please try now.

**Comment by lafita** [comment]
It works fine now, thanks Matt!
