### ISSUE TITLE
R version to old

### ISSUE THREAD

**Issue by openpaul** [EBI-predocs/research-software#74]
As far as I noticed the R version is 3.4. 

This should be updated to the latest version. 
Alternatively a later version should be installed along side as R-3.5 or equivalent.

```
/nfs/software/software/prefix/usr/bin/R
# R version 3.4.1 (2017-06-30) -- "Single Candle" 
```
Newest R is 3.5

**Comment by openpaul** [comment]
This would be cool as I have issues using bioconductor packages

**Comment by lafita** [comment]
I am working on updating all packages so this should be solved soon!

**Comment by lafita** [comment]
R is on `3.5.1` now!
