### ISSUE TITLE
R cant install packages

### ISSUE THREAD

**Issue by openpaul** [EBI-predocs/research-software#75]
R does not have a (working) mirror of CRAN configured. 

```
Installing package into ‘/homes/saary/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://mirrors.ebi.ac.uk/CRAN/src/contrib:
  cannot open URL 'https://mirrors.ebi.ac.uk/CRAN/src/contrib/PACKAGES'
Warning message:
```

My workaround is using the rstudio CRAN mirror:

https://blog.rstudio.com/2013/06/10/rstudio-cran-mirror/

```R
options(repos = c(CRAN = "http://cran.rstudio.com"))

```

**Comment by lafita** [comment]
Yeah the mystery of the lost EBI CRAN mirror... I will search for the configuration file that sets the mirror so it is updated for all users, but you can choose your user spcecific one in `~/.Rprofile`.
